[project]
name        = 'rx_data'
description = 'Project with lists of LFNs and utilities needed to download filteres ntuples' 
version     = '0.0.1'
readme      = 'README.md'
dependencies= []

[project.optional-dependencies]
dev  = ['pytest']

[tools.setuptools.packages.find]
where   = ['src']

[tool.setuptools.package-data]
'rx_data_lfns' = ['*.json']

